service: nestjs-serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  main:
    handler: src/main-lambda.handler
    events:
      - http:
          path: /
          method: get
