AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  csw24-grupob

  Sample SAM Template for csw24-grupob
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../
      Handler: ./src/main.lambdaHello
      Runtime: nodejs18.x
      Role: arn:aws:iam::055848354853:role/LabRole
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/main.ts
        External:
          - "@nestjs/microservices"
          - "@nestjs/websockets"
          - "class-transformer"
          - "class-validator"

  # TicketsFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: ../
  #     Handler: ./src/main.lambdaHandler
  #     Runtime: nodejs18.x
  #     Role: arn:aws:iam::055848354853:role/LabRole
  #     Architectures:
  #       - x86_64
  #     Events:
  #       Tickets:
  #         Type: Api
  #         Properties:
  #           Path: /{proxy+}
  #           Method: any
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints: 
  #       - src/main.ts

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  # TicketsFunction:
  #   Description: "Tickets Lambda Function ARN"
  #   Value: !GetAtt TicketsFunction.Arn
